version: '3'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=file_storage_service
      - POSTGRES_DB=file_storage_service_development
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"

  app:
    build: .
    environment:
      DB_HOST: db
      DB_USERNAME: file_storage_service
      DB_PASSWORD: password
    ports:
      - "3000:3000"
    depends_on:
      - db
    restart: always

  redis:
    image: redis:7.0.4
    environment:
      - REDIS_DB=0
    ports:
      - "6379:6379"