default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: password

development:
  <<: *default
  database: file_storage_service_development

test:
  <<: *default
  database: file_storage_service_test

production:
  <<: *default
  database: file_storage_service_production
  username: file_storage_service
  password: <%= ENV['FILE_STORAGE_SERVICE_DATABASE_PASSWORD'] %>