default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['DB_HOST'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>

development:
  <<: *default
  database: file_storage_service_development

test:
  <<: *default
  database: file_storage_service_test

production:
  <<: *default
  database: file_storage_service_production