default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: <%= ENV['DB_PASSWORD'] %>
  port: 5432

development:
  <<: *default
  database: file_storage_service_development

test:
  <<: *default
  database: file_storage_service_test

production:
  <<: *default
  database: file_storage_service_production
  pool: 5
  timeout: 5000